export const enum Genre {
  MartialArts = "Боевые искусства",
  Vampires = "Вампиры",
  Harem = "Гарем",
  Demons = "Демоны",
  Detective = "Детектив",
  Josei = "Дзёсей",
  Drama = "Драма",
  Games = "Игры",
  Isekai = "Исекай",
  Historical = "Исторический",
  Cyberpunk = "Киберпанк",
  Comedy = "Комедия",
  Magic = "Магия",
  Mecha = "Меха",
  Mystery = "Мистика",
  Music = "Музыка",
  Parody = "Пародия",
  SliceOfLife = "Повседневность",
  Adventure = "Приключения",
  Psychological = "Психологическое",
  Romance = "Романтика",
  Supernatural = "Сверхъестественное",
  Shoujo = "Сёдзе",
  ShoujoAi = "Сёдзе-ай",
  Seinen = "Сэйнэн",
  Shounen = "Сёнен",
  ShounenAi = "Сёнен-ай",
  Sports = "Спорт",
  SuperPower = "Супер сила",
  Thriller = "Триллер",
  Horror = "Ужасы",
  SciFi = "Фантастика",
  Fantasy = "Фэнтези",
  School = "Школа",
  Action = "Экшен",
  Ecchi = "Этти",
}

export const TagColors: Record<string, [string, string]> = {
  Processing: ["rgb(24, 144, 255)", "rgba(24, 144, 255, .2)"],
  Success: ["rgb(82, 196, 26)", "rgba(82, 196, 26, .2)"],
  Error: ["rgb(245, 34, 45)", "rgba(245, 34, 45, .2)"],
  Warning: ["rgb(250, 173, 20)", "rgba(250, 173, 20, .2)"],
  Magenta: ["rgb(235, 47, 150)", "rgba(235, 47, 150, .2)"],
  Red: ["rgb(255, 78, 78)", "rgba(255, 78, 78, .2)"],
  Volcano: ["rgb(250, 84, 28)", "rgba(250, 84, 28, .2)"],
  Orange: ["rgb(250, 140, 22)", "rgba(250, 140, 22, .2)"],
  Gold: ["rgb(250, 173, 20)", "rgba(250, 173, 20, .2)"],
  Lime: ["rgb(160, 217, 17)", "rgba(160, 217, 17, .2)"],
  Green: ["rgb(82, 196, 26)", "rgba(82, 196, 26, .2)"],
  Cyan: ["rgb(19, 194, 194)", "rgba(19, 194, 194, .2)"],
  Blue: ["rgb(4, 0, 255)", "rgba(4, 0, 255, .2)"],
  Geekblue: ["rgb(47, 84, 235)", "rgba(47, 84, 235, .2)"],
  Purple: ["rgb(114, 46, 209)", "rgba(114, 46, 209, .2)"],
};

export const colorByGenre: Record<Genre, [string, string]> = {
  [Genre.MartialArts]: TagColors.Red,
  [Genre.Vampires]: TagColors.Magenta,
  [Genre.Harem]: TagColors.Gold,
  [Genre.Demons]: TagColors.Red,
  [Genre.Detective]: TagColors.Blue,
  [Genre.Josei]: TagColors.Magenta,
  [Genre.Drama]: TagColors.Red,
  [Genre.Games]: TagColors.Cyan,
  [Genre.Isekai]: TagColors.Green,
  [Genre.Historical]: TagColors.Orange,
  [Genre.Cyberpunk]: TagColors.Cyan,
  [Genre.Comedy]: TagColors.Green,
  [Genre.Magic]: TagColors.Purple,
  [Genre.Mecha]: TagColors.Geekblue,
  [Genre.Mystery]: TagColors.Volcano,
  [Genre.Music]: TagColors.Lime,
  [Genre.Parody]: TagColors.Orange,
  [Genre.SliceOfLife]: TagColors.Lime,
  [Genre.Adventure]: TagColors.Cyan,
  [Genre.Psychological]: TagColors.Purple,
  [Genre.Romance]: TagColors.Magenta,
  [Genre.Supernatural]: TagColors.Purple,
  [Genre.Shoujo]: TagColors.Magenta,
  [Genre.ShoujoAi]: TagColors.Purple,
  [Genre.Seinen]: TagColors.Geekblue,
  [Genre.Shounen]: TagColors.Orange,
  [Genre.ShounenAi]: TagColors.Magenta,
  [Genre.Sports]: TagColors.Green,
  [Genre.SuperPower]: TagColors.Orange,
  [Genre.Thriller]: TagColors.Volcano,
  [Genre.Horror]: TagColors.Purple,
  [Genre.SciFi]: TagColors.Cyan,
  [Genre.Fantasy]: TagColors.Geekblue,
  [Genre.School]: TagColors.Red,
  [Genre.Action]: TagColors.Red,
  [Genre.Ecchi]: TagColors.Magenta,
};
