export const enum Properties {
  id = "id",
  names = "names",
  description = "description",
  code = "code",
  franchises = "franchises",
  announce = "announce",
  status = "status",
  posters = "posters",
  updated = "updated",
  last_change = "last_change",
  type = "type",
  genres = "genres",
  team = "team",
  season = "season",
  in_favorites = "in_favorites",
  blocked = "blocked",
  player = "player",
  torrents = "torrents",
}
